### ISSUE TITLE
Get the circles to show up on candidate pages

### ISSUE THREAD

**Issue by dianezeigler** [thinkorsink/vtdigs#13]
![screen shot 2016-07-28 at 10 59 34 am](https://cloud.githubusercontent.com/assets/20703702/17217440/65781532-54b2-11e6-9729-945af387534f.png)

**Comment by thinkorsink** [comment]
Can I propose this as an alternative.

![question-wheel](https://cloud.githubusercontent.com/assets/788180/17220435/34bb9440-54bd-11e6-8b3a-00947a648939.jpg)

**Comment by dianezeigler** [comment]
how about we put the first two and last two closer together so it looks more like a circle?

**Comment by thinkorsink** [comment]
OK that could work. I'll let you know what I come up with.

**Comment by dianezeigler** [comment]
you might want to put the text underneath the question mark so it is easier to center them

**Comment by dianezeigler** [comment]
would super love to have dashed lines connecting them

**Comment by thinkorsink** [comment]
OK. I've got a prototype up. It know it needs a little tweaking.

**Comment by dianezeigler** [comment]
you are prob tweaking this but if you move the top two and bottom two closer to each other that would work better
![screen shot 2016-07-28 at 2 56 46 pm](https://cloud.githubusercontent.com/assets/20703702/17225602/a740c45c-54d3-11e6-8d90-f31901dd2b24.png)
