### ISSUE TITLE
Can we have the issues populate on the candidate pages or do we need to reenter them

### ISSUE THREAD

**Issue by dianezeigler** [thinkorsink/vtdigs#14]
![screen shot 2016-07-28 at 11 52 55 am](https://cloud.githubusercontent.com/assets/20703702/17219721/58eae72e-54ba-11e6-81b8-048c5c82d10d.png)

**Comment by thinkorsink** [comment]
No need to re-enter Just a little bug I need to fix. But that is what a bug
tracker is for.

**Comment by thinkorsink** [comment]
FIXED

**Comment by dianezeigler** [comment]
sorry if this was already in your bug list.

**Comment by thinkorsink** [comment]
I just meant there was no need to re-enter the issue. This was a perfect
example of something for the bug tracker. Can you go through some of the
ones that I bugs that I assigned to you and answer the questions that I put
on them.

I think this system is working. Yay!

**Comment by dianezeigler** [comment]
yes i’m seeing that and am closing things out and responding. this is so much better. thanks
