### ISSUE TITLE
Primary Page: Put read more link on the same line as the text in the field

### ISSUE THREAD

**Issue by dianezeigler** [thinkorsink/vtdigs#16]
This way it doesn't mess up spacing in the left column between the candidates

![screen shot 2016-07-28 at 1 15 55 pm](https://cloud.githubusercontent.com/assets/20703702/17222297/8da59788-54c5-11e6-89b8-f09c0389ca6c.png)

**Comment by thinkorsink** [comment]
FIXED!

**Comment by dianezeigler** [comment]
very elegant thank you
