### ISSUE TITLE
Candidate Page: link state for question

### ISSUE THREAD

**Issue by dianezeigler** [thinkorsink/vtdigs#17]
1) Get the circle to be blue so you know what question you're on.
2) Change the "see all issues" link to say "Back to issues list" and then add text next to it to say "or scroll through the questions numbered above"
![screen shot 2016-07-28 at 2 22 05 pm](https://cloud.githubusercontent.com/assets/20703702/17224469/02e56768-54cf-11e6-9335-0a1f3679399f.png)

**Comment by thinkorsink** [comment]
Fixed 2.
 1 is waiting on a little more Javascript help.

**Comment by dianezeigler** [comment]
ADD A PERIOD.
![screen shot 2016-07-28 at 2 42 13 pm](https://cloud.githubusercontent.com/assets/20703702/17225105/9045fc06-54d1-11e6-8494-7f0ebe2ad03c.png)

**Comment by dianezeigler** [comment]
ALSO I JUST THOUGHT OF AN EASY FIX: remove the circled numbers of the questions above upon viewing the answer!!!   Then you don't have to deal with the javascript and you can change the link back to the way it was: 'back to issues list'

just get rid of the numbers.

![screen shot 2016-07-28 at 2 44 18 pm](https://cloud.githubusercontent.com/assets/20703702/17225161/cb2a491c-54d1-11e6-87dc-3ea2ffa37309.png)

![screen shot 2016-07-28 at 2 44 45 pm](https://cloud.githubusercontent.com/assets/20703702/17225233/14307a64-54d2-11e6-93b9-d84403f727c3.png)

**Comment by thinkorsink** [comment]
FIXED!
