### ISSUE TITLE
Bad news: Primary Page read more needs tweaks on subsequent questions

### ISSUE THREAD

**Issue by dianezeigler** [thinkorsink/vtdigs#19]
here's q1 which is lovely.  below that is q2
![screen shot 2016-07-28 at 3 06 39 pm](https://cloud.githubusercontent.com/assets/20703702/17225947/040bc0f0-54d5-11e6-9dbf-3f3bcaa9ded2.png)

![screen shot 2016-07-28 at 3 06 45 pm](https://cloud.githubusercontent.com/assets/20703702/17225952/07db4214-54d5-11e6-85b9-632b315a30ac.png)

**Comment by thinkorsink** [comment]
Woops. I had tested the first one to see if it worked and forgot to do the rest. FIXED now!
