### ISSUE TITLE
the sun is a bad link to a 404

### ISSUE THREAD

**Issue by dianezeigler** [thinkorsink/vtdigs#23]
http://vtdigger.org/wp-content/themes/vtdigger-2013/images/icon-sun-bg.png
![screen shot 2016-07-28 at 5 46 01 pm](https://cloud.githubusercontent.com/assets/20703702/17230617/2ca5628a-54eb-11e6-9c77-133e7f72829d.png)

**Comment by thinkorsink** [comment]
Just hadn't uploaded it yet.
