### ISSUE TITLE
Adding info to the excerpt makes the image fail to wrap

### ISSUE THREAD

**Issue by dianezeigler** [thinkorsink/vtdigs#28]
![screen shot 2016-08-01 at 4 26 35 pm](https://cloud.githubusercontent.com/assets/20703702/17308073/1293d368-5806-11e6-89d0-74dda71a35c2.png)

**Comment by dianezeigler** [comment]
I am removing the excerpt code now but I wanted you to see that it had been in there and what the page looked like.
![screen shot 2016-08-01 at 4 37 05 pm](https://cloud.githubusercontent.com/assets/20703702/17308101/3430e3f8-5806-11e6-8b3a-1dce46642e42.png)

**Comment by thinkorsink** [comment]
This is now fixed.
