### ISSUE TITLE
please format this field to have a p tag for the css

### ISSUE THREAD

**Issue by thinkorsink** [thinkorsink/vtdigs#3]
note that spaces in the field do not show as spaces in the text.  (see the period after the word costs and Additionally.

![unnamed](https://cloud.githubusercontent.com/assets/788180/17194706/618c4492-5427-11e6-954c-dffa31b20d0d.png)

**Comment by thinkorsink** [comment]
Just add a `<br>` to create some space. I also messed the content of this up under Kesha's page.

**Comment by dianezeigler** [comment]
I will see if adding break tags for gov candidates will work.  This is a light guv issue, and the word additionally is cut off as are others.

![screen shot 2016-07-28 at 12 31 07 pm](https://cloud.githubusercontent.com/assets/20703702/17220878/4bf6f5ee-54bf-11e6-800e-547962ba11d2.png)
