### ISSUE TITLE
Add numbers to the question responses:

### ISSUE THREAD

**Issue by dianezeigler** [thinkorsink/vtdigs#31]
Put numbers in circles to the left of the responses

![screen shot 2016-09-17 at 3 52 54 pm](https://cloud.githubusercontent.com/assets/20703702/18610622/d38e6bca-7cee-11e6-9667-ce979cae9548.png)
  Maybe use something like this only a little smaller?

![screen shot 2016-09-17 at 3 54 03 pm](https://cloud.githubusercontent.com/assets/20703702/18610634/fff149c6-7cee-11e6-8792-bc0cc3a1489b.png)

**Comment by thinkorsink** [comment]
Added numbers. Check and see if you approve.
