### ISSUE TITLE
Campaign finance link in circle is wrong

### ISSUE THREAD

**Issue by dianezeigler** [thinkorsink/vtdigs#32]
from house and senate pages, clicking this link doesn't work correctly. You end up with this message:
![screen shot 2016-09-17 at 4 20 53 pm](https://cloud.githubusercontent.com/assets/20703702/18610777/c7a08902-7cf2-11e6-9fb8-cf518256b958.png)

![screen shot 2016-09-17 at 4 23 03 pm](https://cloud.githubusercontent.com/assets/20703702/18610792/0b37a092-7cf3-11e6-9398-f84ce9e90274.png)

HOWEVER THIS LINK ON THE LANDING PAGE WORKS RIGHT
![screen shot 2016-09-17 at 4 24 47 pm](https://cloud.githubusercontent.com/assets/20703702/18610798/4947ab5c-7cf3-11e6-9988-cba6dae3172c.png)

IT RESOLVES TO http://vtdigger.org/data/campaign-finance/campaign-finance-candidate-results/?candidate_id=99990039&cycle=2015-2016

**Comment by thinkorsink** [comment]
Fixed. The ones that work on the listing page also work from the individual pages.
