### ISSUE TITLE
Add some kind of filtering for house and senate by name and zip code?

### ISSUE THREAD

**Issue by dianezeigler** [thinkorsink/vtdigs#33]
Let's discuss whether we could have a search by feature. Some ideas can be found here. I like the idea of filtering by name, district, party, or chamber.

http://vtdigger.org/data/legislator-lookup/

![screen shot 2016-09-17 at 5 57 36 pm](https://cloud.githubusercontent.com/assets/20703702/18611205/617e2fb8-7d00-11e6-8a01-94b1c5ee58f4.png)

**Comment by thinkorsink** [comment]
I did the simplest version possible. Take a look and see what you think.
