### ISSUE TITLE
create flag for incumbents on landing page

### ISSUE THREAD

**Issue by dianezeigler** [thinkorsink/vtdigs#37]
Maybe just red text next to their names? Not sure, here's a flat icon example. At the bottom is a gif of a file you could use for this purpose. It would need red text underneath it to say Incumbent.

![screen shot 2016-09-18 at 4 06 20 pm](https://cloud.githubusercontent.com/assets/20703702/18618694/dec73bcc-7db9-11e6-88e1-40cc794ad4c3.png)

![incumbent](https://cloud.githubusercontent.com/assets/20703702/18618708/1429be48-7dba-11e6-8eee-704d2a94122d.gif)

**Comment by thinkorsink** [comment]
Fixed.
