### ISSUE TITLE
Errors in Excel

### ISSUE THREAD

**Issue by thinkorsink** [thinkorsink/vtdigs#44]
Scott Campbell is not an incumbent

Two Entries

Mary E Howard
Mary Elena Howard
(Same Person)

**Comment by dianezeigler** [comment]
oh shit, we need to delete the one that doesn’t have a link to CFD. great catch sam

**Comment by thinkorsink** [comment]
Did you fix this? Because we can close the issue if you have.

You can see I really like closing issues.
