### ISSUE TITLE
Add a field for "endorsed by" for statewides, only showing up if there is content

### ISSUE THREAD

**Issue by dianezeigler** [thinkorsink/vtdigs#61]
Perhaps we could do this under the contact info

![screen shot 2016-10-05 at 9 37 19 am](https://cloud.githubusercontent.com/assets/20703702/19115274/5a9d2194-8adf-11e6-81de-90927600c891.png)

**Comment by dianezeigler** [comment]
This field can just be a text field, and can be populated by hand; i don't see the need to upload the whole thing....but open to your suggestions

**Comment by dianezeigler** [comment]
To clarify, I think this should be a blue header field and then text populating it beneath i think. We should discuss this one....

**Comment by thinkorsink** [comment]
Added. Field is cand-endorsements
