### ISSUE TITLE
Tom Licata tagging

### ISSUE THREAD

**Issue by dianezeigler** [thinkorsink/vtdigs#64]
Below is a screenshot of the Tom Licata items. Here are the issues:
1. First two items are dups. I have no idea how to fix this.
2. Tom says that this item he wrote is missing from the list below, which it is, but I can't figure out what because it's tagged in the same way: [http://vtdigger.org/2010/09/02/licata-vermont-and-the-nation-face-structural-economic-changes/]

Here's the screenshot
![screen shot 2016-10-06 at 9 36 57 am](https://cloud.githubusercontent.com/assets/20703702/19154415/72a8eb0a-8ba8-11e6-8f3a-d9f5e5b42831.png)

**Comment by thinkorsink** [comment]
Fixed. I made it so it shows the last 10 commentaries rather than just the last 5.

**Comment by dianezeigler** [comment]
thanks a ton
