### ISSUE TITLE
Thursday 10/6 - top thing to work on

### ISSUE THREAD

**Issue by dianezeigler** [thinkorsink/vtdigs#65]
1) Get US Senate and US House in there
2) Get other data (videos, comparative answers) out of the database - I need to update the videos

**Comment by thinkorsink** [comment]
I can bust all this statewide stuff out tomorrow. Downloading the file now.

**Comment by thinkorsink** [comment]
House and Senate all set up on staging site. Tag for Senator is "US Senator" and tag for Congress is "Representative to Congress"

**Comment by thinkorsink** [comment]
Ready to go here.
