### ISSUE TITLE
Need more padding on Issues  

### ISSUE THREAD

**Issue by thinkorsink** [thinkorsink/vtdigs#7]
![unnamed-2](https://cloud.githubusercontent.com/assets/788180/17194901/a14bf8ce-5428-11e6-8710-487e5abb9ed5.png)

**Comment by thinkorsink** [comment]
Can you be more specific? Padding on the bottom? Is it OK everywhere else?

**Comment by dianezeigler** [comment]
please note that the screenshot indicates the text is cut off (see first line on the word available).  This is for the candidate page, just for clarity.  There is a different issue going on with the primary page for the longform answer, which I created an item for.

**Comment by thinkorsink** [comment]
The words getting cutting off is fixed. But does it need more padding as well???

**Comment by dianezeigler** [comment]
no its fine
