### ISSUE TITLE
Get issues to show up on primary page

### ISSUE THREAD

**Issue by dianezeigler** [thinkorsink/vtdigs#8]
![screen shot 2016-07-28 at 9 57 43 am](https://cloud.githubusercontent.com/assets/20703702/17215094/c3b9a45c-54a9-11e6-8ddc-7d305739d66b.png)

**Comment by thinkorsink** [comment]
Nice job. Exactly.

**Comment by dianezeigler** [comment]
## this will be super easier and will make you like me more, which is a priority for me.

Diane Zeigler
Publisher
VTDigger.org
97 State Street, Montpelier, VT 05602
802.839.6520 (cell)
802.225.6224 (office)
@dianezeigler on Twitter and LinkedIn

**Comment by thinkorsink** [comment]
Bam! Closed that issue!

**Comment by dianezeigler** [comment]
Yay!!!

---

Typos courtesy of my iPhone.

Diane Zeigler
Publisher
VTDigger.org
802-839-6520 (cell)
